MusID__First = 1
	enum MusID_TestSong1=MusID__First,MusID_Title,MusID_2PResult,MusID_Options,MusID_GHZ,MusID_EHZ,MusID_GRGZ1
	enum MusID_GRGZ2=MusID_GRGZ1+1,MusID_ALZ,MusID_CPZ,MusID_GGZ1,MusID_GGZ2,MusID_ARZ,MusID_RRZ1
	enum MusID_RRZ2=MusID_RRZ1+1,MusID_HTZ,MusID_DDZ1,MusID_DDZ2,MusID_ICZ1,MusID_ICZ2,MusID_LZ
	enum MusID_HPZ=MusID_LZ+1,MusID_OOZ,MusID_MTZ,MusID_PPZ1,MusID_PPZ2,MusID_LBZ1_S3,MusID_LBZ2_S3
	enum MusID_SBZ=MusID_LBZ2_S3+1,MusID_DEZ,MusID_Boss,MusID_Boss2,MusID_Boss3,MusID_EndBoss,MusID_Ending_S1
	enum MusID_Ending_S2=MusID_Ending_S1+1,MusID_Credits,MusID_Credits_2,MusID_BonusStage,MusID_BonusStage2,MusID_BonusStage3,MusID_SpecialStage
	enum MusID_Invincible=MusID_SpecialStage+1,MusID_SuperSonic,MusID_Test6,MusID_Test7,MusID_EHZ_2P,MusID_SW_HPZ,MusID_CNZ_2P
	enum MusID_SCZ=MusID_CNZ_2P+1,MusID_EndLevel,MusID_GameOver,MusID_ExtraLife,MusID_DoubleLife,MusID_Continue,MusID_Emerald
	enum MusID_Countdown=MusID_Emerald+1,MusID__End