MusID__First = 1
	enum MusID_TestSong1=MusID__First,MusID_TestSong2,MusID_Title,MusID_2PResult,MusID_Options,MusID_GHZ,MusID_EHZ
	enum MusID_GRGZ1=MusID_EHZ+1,MusID_GRGZ2,MusID_ALZ,MusID_CPZ,MusID_GGZ1,MusID_GGZ2,MusID_ARZ
	enum MusID_RRZ1=MusID_ARZ+1,MusID_RRZ2,MusID_HTZ,MusID_DDZ1,MusID_DDZ2,MusID_ICZ1,MusID_ICZ2
	enum MusID_LZ=MusID_ICZ2+1,MusID_HPZ,MusID_OOZ,MusID_MTZ,MusID_PPZ1,MusID_PPZ2,MusID_LBZ1_S3
	enum MusID_LBZ2_S3=MusID_LBZ1_S3+1,MusID_SBZ,MusID_DEZ,MusID_Boss,MusID_Boss2,MusID_Boss3,MusID_EndBoss
	enum MusID_Ending_S1=MusID_EndBoss+1,MusID_Ending_S2,MusID_Credits,MusID_Credits_2,MusID_BonusStage,MusID_BonusStage2,MusID_BonusStage3
	enum MusID_SpecialStage=MusID_BonusStage3+1,MusID_Invincible,MusID_SuperSonic,MusID_Test6,MusID_Test7,MusID_EHZ_2P,MusID_SW_HPZ
	enum MusID_CNZ_2P=MusID_SW_HPZ+1,MusID_SCZ,MusID_EndLevel,MusID_GameOver,MusID_ExtraLife,MusID_DoubleLife,MusID_Continue
	enum MusID_Emerald=MusID_Continue+1,MusID_Countdown,MusID__End